[project]
name = "party-organiser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic==1.14",
    "fastapi[standard]==0.115.11",
    "pytest==8.3",
    "sqlmodel==0.0.24",
]
